# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@3
inputs:
    azureSubscription: 'd6327f0f-a8f5-4a20-a651-3020e65a158b'
    ScriptPath: 'azdemopipeline/script.ps1'
    ScriptArguments: -ResourceGroupName 'Anudnya_RG2' -ResourceGroupLocation 'centralus'
    azurePowerShellVersion: LatestVersion